{% set name = "dbf" %}
{% set version = "0.99.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 5002bb7a579a5302d3db63738efe3e9d2532ea54a6f630176d3526416ffe00a2

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python
    - pip
    - wheel
    - setuptools
  run:
    - python
    - aenum

test:
  imports:
    - dbf
  commands:
    - pip check
    # Run only tests which not try to create a tempdir.
    # Tests with tempdir need to generate a temptable.
    # No example of how to generate it in the upstream.
    - pytest -v ${SP_DIR}/dbf/test.py::TestChar ${SP_DIR}/dbf/test.py::TestDateTime ${SP_DIR}/dbf/test.py::TestDateTime ${SP_DIR}/dbf/test.py::TestLogical ${SP_DIR}/dbf/test.py::TestQuantum  # [unix]
    - pytest -v %SP_DIR%/dbf/test.py::TestChar %SP_DIR%/dbf/test.py::TestDateTime %SP_DIR%/dbf/test.py::TestDateTime %SP_DIR%/dbf/test.py::TestLogical %SP_DIR%/dbf/test.py::TestQuantum  # [win]
  requires:
    - pip
    - pytest
    - pytz

about:
  home: https://github.com/ethanfurman/dbf
  license: BSD-3-Clause
  license_family: BSD
  license_file: dbf/LICENSE
  summary: Pure python package for reading/writing dBase, FoxPro, and Visual FoxPro .dbf files (including memos)
  description: |
    Dbf is a pure Python package for reading/writing dBase, FoxPro, and
    Visual FoxPro .dbf files. Currently supports dBase III, Clipper, FoxPro,
    and Visual FoxPro tables. Text is returned as unicode, and codepage settings
    in tables are honored.
  doc_url: https://github.com/ethanfurman/dbf/blob/master/dbf/README.md
  dev_url: https://github.com/ethanfurman/dbf

extra:
  recipe-maintainers:
    - synapticarbors
