travis:
  secure:
    BINSTAR_TOKEN: Ss8OIiyCEvxSi3stljtR212VWdxoyrqgs7vASTPD2cfOS5BBrgCR5cC7+D+F+CgfNRsQww/NVaicMQAYzANYHJxS/osNZTl+f4CZIvpwv3k3rTgTPysK8SQODDxWFY/2nm37OKwvbiT6gB3LCBbQIKH5DtRv5RNQDWFwEP0Z6dNUZPgOzIkq6UMSknFWV3bnG7XqfAi8rXTj5MBpHMa8nUTamUPcjjwyVqML+OwqNQvZ1fiMuM1Fulgi82sL3pn/8YM3U54A+3Y0fJAiVOmV0RDOgXD0uFinVcTnxS3J9/EVbHfjNMShwdOJ1aJWyL8qZ43XKUypKHLZi0SyauF9OJrUtuBrxK0GFDZfwFeJA0PHD98T4EBK6y+xxoNhC71Q5Pr4FcrVSK7dBBVemJBSSBUWmIJrhNuSCE9AfHXVPxmb3g9EOUvp1ab2//nqu/1MaH/yGKRUjzPfGF8dMcPxaZg+OF4OX4KGmanHffw3V0UvmVaGzGo9IkIcbvjLvur27tIWRhoSWrWIib6blyvMOwZPy/3Y/86fqb+A+C3Bzn3u2FGIepyRsHRjMh7dUZxr1nWX2/tvGJlCErJFoks0jnZRt3jt/hZNJfHBZV3USTK5Lh4ygT8tN3SX0JGII83Pq6Hx0VcsqjysYnOk3JvobZVhuQxf0u9brnEGB2CJ53U=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
