travis:
  secure:
    BINSTAR_TOKEN: J5xauiQwVwwbayYqjqdJc18UuZGkFiAQPGe2Gli45JfIQ7MqL+1a84+xUkHwbQcbP6vuhtxT4c9QE+9wtVfvG2cH2lBE5cN0yWJ+DGUlLlbTuqgO4qx28grOBTwM/XusI+GVyRr+59kH7xZUy6c/zxC57GYbwdkWZwWUBzdQuW5DS4gWlTzBa5VJ5kzniSgDBd4si0jdUdt0GywDHbQlOmrJG1jAzKUPKUG2+3gTKbekyO1F/coftpdXZUwZUE8TFHkmFsOkBgzVO5uragIwx3aPaku86mnEbhO2lqJF2zzhofPDkMwKk9LFlza7e4vV8I4bky/HoJHc/sssgCqnZid3wIbb/pvjl9m0lDN6gW62/a+NYMoKj6I2iMcXFtM2EPfbB+dS0lSsvI1PODGw6qA9o92fNHlMq/if+w26TRmtXk8i2NjnLkFKgFgnIeAMJ6DG6rZfSbou2PoICJB47PH9LXItljNS2ZNzgUmB4Ex6nxqZ4H9WTv7JIVMNOQ/n7B3ILMedrghkWKunOakt4vh6IHSu6s7Y5IsWOeFidbIy2Myni4M96sC2nEUHkbncRmiFMg5pPJtsW27L3fTp8DyuPffo42//tXs3Y2RyCM0XOtAQ0qWfDT+03ta2Jz+5wDGsR5w6DiPEBUWYk5Q45gpLHqlf4HljutJVNuMXGQg=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
